language: julia
os: linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
codecov: true
jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
